version: '3.1'
services:
  app:
    build: .
    ports:
     - "4567:4567"
    command: tail -F anything
    volumes:
     - ./code:/usr/src/app/
    links:
     - db
  db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: example
