version: '3.1'
services:
  web:
    build: .
    ports:
     - "8080:80"
    volumes:
     - ./www:/var/www/site/
    links:
     - db
  db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: example
